services:
  warehouse:
    build: .
    container_name: warehouse-app
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:9095
      - ConnectionStrings__DefaultConnection=Server=sql2019,1433;Database=WarehouseDB;User Id=sa;Password=2219@Atomtneda;TrustServerCertificate=True;
      - VIRTUAL_HOST=warehouse.yourdomain.com
      - VIRTUAL_PORT=9095
      - LETSENCRYPT_HOST=warehouse.yourdomain.com
      - LETSENCRYPT_EMAIL=your@email.com
    networks:
      - shared-network

networks:
  shared-network:
    external: true
